name: Build and Push Image
on:
  ## must be run manually to push image
  workflow_dispatch:
    jobs:
      Push image:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Files
          uses: actions/checkout@v2
        - name: Build and Push Image
          uses: docker/build-push-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: NOAA-GFDL/FRE-NCtools-container/fre-nctools-base
            tag_with_ref: true
  ## test successful build from file
  push:
    jobs:
      Test build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Files
          uses: actions/checkout@v2
        - name: Build image
          run: docker build .
