## test successful build from file
name: Test Dockerfile build
on: [push, pull_request]
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Build image
      run: docker build .
